//=========================================================
// src/SPI proba_main.c: generated by Hardware Configurator
//
// This file will be updated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================

//-----------------------------------------------------------------------------
// Includes
//-----------------------------------------------------------------------------
#include <SI_EFM8SB2_Register_Enums.h>                  // SFR declarations
#include "InitDevice.h"
// $[Generated Includes]
// [Generated Includes]$

//-----------------------------------------------------------------------------
// SiLabs_Startup() Routine
// ----------------------------------------------------------------------------
// This function is called immediately after reset, before the initialization
// code is run in SILABS_STARTUP.A51 (which runs before main() ). This is a
// useful place to disable the watchdog timer, which is enable by default
// and may trigger before main() in some instances.
//-----------------------------------------------------------------------------
void SiLabs_Startup (void)
{
  // $[SiLabs Startup]
  // [SiLabs Startup]$
}


#define LIS3DH_REG_CTRL_REG1 0x20
#define LIS3DH_RW_BIT_WRITE 0x00
#define LIS3DH_REG_CTRL_REG1    0x20
#define LIS3DH_REG_CTRL_REG4    0x23
#define LIS3DH_REG_CTRL_REG5    0x24
#define LIS3DH_REG_CTRL_REG3    0x22
#define LIS3DH_REG_INT1_CFG     0x30
#define LIS3DH_REG_INT1_THS     0x32
#define LIS3DH_REG_INT1_DURATION 0x33
#define LIS3DH_REG_STATUS_REG 0x27
#define LIS3DH_RW_BIT_READ 0x80
#define LIS3DH_RW_BIT_WRITE 0x00

#define LIS3DH_REG_OUT_X_H 0x29
#define LIS3DH_REG_OUT_Y_H 0x2B
#define LIS3DH_REG_OUT_Z_H 0x2D
#define LIS3DH_REG_OUT_X_L 0x28
#define LIS3DH_REG_OUT_Y_L 0x2A
#define LIS3DH_REG_OUT_Z_L 0x2C

#define NSS P1_B3

// SPI port inicializálása
void SPI_Init()
{
    SPI0CFG = 0x40;     // Master üzemmód, SPI0CLK/4
    SPI0CN0 = 0x01;     // SPI port engedélyezése
    P0MDOUT |= 0x13;    // P0.0, P0.1 és P0.3 kimenetek SPI számára
}

// SPI adat küldése
uint8_t SPI_Write(uint8_t adat)
{
    NSS= 0;
    SPI0DAT = adat;                   // Adat beállítása az adatregiszterbe
    while(!(SPI0CN0 & 0x80));         // Várakozás, amíg az SPIF bit beáll
    SPI0CN0 &= ~0x80;                 // SPIF bit nullázása
    NSS=1;
    return SPI0DAT;                   // Válasz beolvasása az adatregiszterből
}
// LIS3DH inicializálása
void LIS3DH_Init()
{
    // CTRL_REG1 beállítása
    SPI_Write(LIS3DH_REG_CTRL_REG1 | LIS3DH_RW_BIT_WRITE);  // Register cím küldése
    SPI_Write(0x47);                                        // CTRL_REG1 beállítása: 100 Hz mintavétel, normál üzemmód, X, Y és Z tengely engedélyezése

    // CTRL_REG4 beállítása
    SPI_Write(LIS3DH_REG_CTRL_REG4 | LIS3DH_RW_BIT_WRITE);  // Register cím küldése
    SPI_Write(0x08);                                        // CTRL_REG4 beállítása: ±2g érzékenység

    // CTRL_REG5 beállítása
    SPI_Write(LIS3DH_REG_CTRL_REG5 | LIS3DH_RW_BIT_WRITE);  // Register cím küldése
    SPI_Write(0x10);  // CTRL_REG5 beállítása: FIFO letiltása, nincs beépített hőmérséklet-szenzor

    // CTRL_REG3 beállítása
    SPI_Write(LIS3DH_REG_CTRL_REG3 | LIS3DH_RW_BIT_WRITE);  // Register cím küldése
    SPI_Write(0x00);                                        // CTRL_REG3 beállítása: nincs beépített FIFO

    // INT1_CFG beállítása
    SPI_Write(LIS3DH_REG_INT1_CFG | LIS3DH_RW_BIT_WRITE);   // Register cím küldése
    SPI_Write(0x00);                                        // INT1_CFG beállítása: interrupt letiltása

    // INT1_THS beállítása
    SPI_Write(LIS3DH_REG_INT1_THS | LIS3DH_RW_BIT_WRITE);   // Register cím küldése
    SPI_Write(0x00);                                        // INT1_THS beállítása: interrupt küszöbértéke 0g

    // INT1_DURATION beállítása
    SPI_Write(LIS3DH_REG_INT1_DURATION | LIS3DH_RW_BIT_WRITE); // Register cím küldése
    SPI_Write(0x00);                                          // INT1_DURATION beállítása: interrupt időkorlát letiltva
}


//-----------------------------------------------------------------------------
// main() Routine
// ----------------------------------------------------------------------------
int main (void)
{
  // Call hardware initialization routine
  enter_DefaultMode_from_RESET();
  
  SPI_Init();

     // LIS3DH inicializálása
     LIS3DH_Init();

     // Főciklus
     while(1)
     {
         int16_t x = 0;
         int8_t x_sift =0;
         int16_t y = 0;
         int16_t z = 0;
         // Adatok beolvasása
         uint8_t status = SPI_Write(LIS3DH_REG_STATUS_REG | LIS3DH_RW_BIT_READ);  // STATUS_REG beolvasása
         if((status & 0x08) == 0x08)  // Ha az adatok frissek
         {
             x_sift =SPI_Write(LIS3DH_REG_OUT_X_H | LIS3DH_RW_BIT_READ) << 8;
             x = (SPI_Write(LIS3DH_REG_OUT_X_H | LIS3DH_RW_BIT_READ) << 8) | SPI_Write(LIS3DH_REG_OUT_X_L | LIS3DH_RW_BIT_READ);  // X tengely beolvasása
             y = (SPI_Write(LIS3DH_REG_OUT_Y_H | LIS3DH_RW_BIT_READ) << 8) | SPI_Write(LIS3DH_REG_OUT_Y_L | LIS3DH_RW_BIT_READ);  // Y tengely beolvasása
             z = (SPI_Write(LIS3DH_REG_OUT_Z_H | LIS3DH_RW_BIT_READ) << 8) | SPI_Write(LIS3DH_REG_OUT_Z_L | LIS3DH_RW_BIT_READ);  // Z tengely beolvasása


         }
     }
}
